# SECRET CONFIGURATION
include "/etc/thehive/secret.conf"

# DATABASE CONFIGURATION
db.janusgraph.storage {
  backend = cql
  hostname = ["cassandra"]
  cql {
    cluster-name = thp
    keyspace = thehive
  }
}

# INDEX DATABASE CONFIGURATION
include "/etc/thehive/index.conf"

# ATTACHMENTS STORAGE CONFIGURATION
storage {
  ## Local filesystem
  provider: localfs
  localfs {
    location: /opt/thp/thehive/files
  }
}

# SERVICE CONFIGURATION
stream.longPolling.refresh: 45 seconds
play.http.context : "/"
play.http.parser.maxDiskBuffer: 1GB
play.http.parser.maxMemoryBuffer: 256kB
### Stream configuration
stream {
  get {
    maxAttempts = 5
    minBackoff = 100 milliseconds
    maxBackoff = 500 milliseconds
    randomFactor = 0.2
  }
}

# MISP Connector Configuration
misp {
  interval = 1m
  "MISP-SERVER" {
    url = "https://172.24.80.95:9001"          # Replace with your MISP URL
    key = "OxrvdAHOfyzDu5kPDeEyT9ui7mW1Wxlxy6D0GtJQ"       # Replace with the MISP API key
    max-attributes = 1000
    max-size = 1 MiB
    max-age = 7 days
    purpose = ImportAndExport
    wsConfig.ssl.loose.acceptAnyCertificate = true
  }
}

cortex {
  "CORTEX_SERVER_NAME" {
    url      = "http://cortex:9001" # Your Cortex URL
    key      = "zE58rzZN9Bxc+yU+I037r2XqmqRrGfAq"
  }
}


# CONNECTORS
# Enable Cortex connector
scalligraph.modules += org.thp.thehive.connector.cortex.CortexModule
# Enable MISP connector
scalligraph.modules += org.thp.thehive.connector.misp.MispModule
