restart-ossec0 - restart-ossec.sh - 0
restart-ossec0 - restart-ossec.cmd - 0
restart-wazuh0 - restart-ossec.sh - 0
restart-wazuh0 - restart-ossec.cmd - 0
restart-wazuh0 - restart-wazuh - 0
restart-wazuh0 - restart-wazuh.exe - 0
netsh0 - netsh.exe - 0
firewall-drop180 - firewall-drop - 180
fim-respond0 - fim-respond.sh - 0
custom-block-ip0 - custom-block-ip.sh - 0
